[ADD] coding_style job

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -4,15 +4,31 @@ on: [push, pull_request]
 env:
   MIRROR_URL: "git@github.com:EpitechPromo2027/B-DOP-200-PAR-2-1-chocolatine-martin.fillon.git"
   EXECUTABLES: "generator/generator,solver/solver"
+  REPORT_FILE: "coding-style-reports.log"
 
 jobs:
   check_coding_style:
     runs-on: ubuntu-latest
-    container: style
+    container:
       image: ghcr.io/epitech/coding-style-checker:latest
     steps:
-      - name: run coding-style
-        run: echo "::set-output name=version::$(check.sh . .)"
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+      - run: |
+        /usr/local/bin/check.sh $(pwd) $(pwd) && cat $REPORT_FILE
+      - run: |
+          cat $REPORT_FILE | while read LINE; do
+            TYPE=$(echo $LINE | cut -d ':' -f 3 | tr -d ' ')
+            FILE=$(echo $LINE | cut -d ':' -f 1)
+            AT=$(echo $LINE | cut -d ':' -f 2)
+            ERROR=$(echo $LINE | cut -d ':' -f 4)
+            echo "::error file=$FILE,line=$AT,title=$TYPE coding style error::$ERROR"
+          done
+          if [[ "$(cat $REPORT_FILE)" != "" ]]; then
+            exit 1
+          fi
+
   push:
     runs-on: ubuntu-latest
     needs: [check_coding_style]
