[ADD] make job

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -3,7 +3,7 @@ run-name: ${{ github.actor }}
 on: [push, pull_request]
 env:
   MIRROR_URL: "git@github.com:EpitechPromo2027/B-DOP-200-PAR-2-1-chocolatine-martin.fillon.git"
-  EXECUTABLES: "generator/generator,solver/solver"
+  EXECUTABLES: "generator/generator,solver/solver,tester"
   REPORT_FILE: "coding-style-reports.log"
 
 jobs:
@@ -29,9 +29,26 @@ jobs:
             exit 1
           fi
 
-  push:
+  make_project:
     runs-on: ubuntu-latest
     needs: [check_coding_style]
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+      - run: |
+          make
+      - run: |
+          for EXECUTABLE in $(echo $EXECUTABLES | tr "," "\n"); do
+            if [[ ! -f $EXECUTABLE ]]; then
+              echo "::error file=Makefile,title=Makefile error::Missing executable $EXECUTABLE"
+              exit 1
+            fi
+          done
+
+  push:
+    runs-on: ubuntu-latest
+    needs: [check_coding_style, make_project]
     steps:
       - uses: actions/checkout@v2
         with:
