[FIX] rm an exit

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -67,6 +67,10 @@ jobs:
           fetch-depth: 0
       - run: |
           timeout 120 make tests_run
+          if [[ $? -ne 0 ]]; then
+            echo "::error file=Makefile,title=Makefile error::Tests failed"
+            exit 1
+          fi
 
   push_to_mirror:
     runs-on: ubuntu-latest
